[package]
name = "odb_poly_decomp"
version = "0.1.0"
edition = "2021"

[lib]
name = "odb_poly_decomp"
path = "src/lib.rs"

[[bin]]
name = "odb_poly_decomp"
path = "src/main.rs"

[dependencies]
id-arena = "2.2.1"
